### ISSUE TITLE
老哥，有时候59分的时候就开始预约

### ISSUE THREAD

**Issue by xidadan** [cunzao/BOOK_SEAT#11]
老哥，第一次运行和今天的时候59分就开始执行预约，是因为约到22：00没有签退造成的吗。
时间：2019-09-05 21:53:41.277640，__main__: 滴滴滴，开始给你盯着位置啦！
时间：2019-09-05 21:59:01.314288，__main__: 开始预约
时间：2019-09-05 21:59:01.315307，job: I'm working...
时间：2019-09-05 21:59:12.365267，__main__: 预约失败
时间：2019-09-05 21:59:17.366665，__main__: 开始预约
时间：2019-09-05 21:59:17.367651，job: I'm working...
时间：2019-09-05 21:59:29.375447，__main__: 预约失败

**Comment by cunzao** [comment]
是59分开始提前准备的，毕竟数据准备什么的都需要时间，跟你没有签退没关系，59分的提示预约失败应该是cookies不正确。。。你能不能把完整的日志发我邮箱: xingdu5436808@163.com，我帮你看看怎么回事。
