### ISSUE TITLE
问题反馈、疑问与功能建议

### ISSUE THREAD

**Issue by if1y** [cunzao/BOOK_SEAT#13]
1. 最近换用Release2.0版本之后，似乎抢不到的几率变大了……？不知道是脚本问题还是怎么，同一个座位，换个没用过脚本的帐号就莫得问题，感觉是被系统半限制了。

1. 由于刚到22点系统很卡，以至于脚本前面五六次请求都是无响应，然后设计的“座位没有就换一个”就根本不会运行，而是连续13次后直接失败。也许可以优化一下这个逻辑？

1. 每个半点（以及某些特殊时间点）都会有座位释放，是否考虑增加一个功能，让脚本在后台轮询捡漏？

1. 现在2.0版本是取消了随机座位功能吗，在注释掉的代码里没找到？

**Comment by cunzao** [comment]
系统逻辑没问题啊，跟上个版本相比没问题，然后你说的座位没有就换一个的特性不运行的问题在我这里没问题啊，能不能提供一下日志发到我的邮箱：xingdu5436808@163.com，随机座位的问题，你是指的前一个版本的randon_seats的那个文件吗？我在重构的时候出了些问题，就没加上去，周末我有空再看看吧！
